spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=PetCareSocialSystem;encrypt=true;trustServerCertificate=true

spring.datasource.username=sa
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
openrouter.api.key=${OPENROUTER_API_KEY}

